Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassVars:
   Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 50

